### PR TITLE
Create Glitched Through Wall

### PR DESCRIPTION
**Pull request by ivandagr8**
Please Help

### CODE REVIEW

**Comment by Load1ng** [comment]
hi

**Comment by Load1ng** [comment]
wanna have sex with me hunny

**Comment by Load1ng** [comment]
if u i will divorce

**Comment by Load1ng** [comment]
:-1:

**Comment by Load1ng** [comment]
:8ball:

**Comment by Load1ng** [comment]
:+1:  :-1:  :100:  :1234:  :8ball:  :) :(

**Comment by Pendragon009** [comment]
same thing happened to me at ragni
i teleported through the wall to the inside because it's hollow

**Pull request closed without merging**
